# Book settings
title: CPSC 430 
author: Firas Moosvi
logo: images/logo.jpg
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md"]
only_build_toc_files: true

bibtex_bibfiles:
  - about/citations.bib

latex:
  latex_documents:
    targetname: book.tex
html:
  home_page_in_navbar : true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  navbar_number_sections : false
  # announcement: "Use this JupyterBook as a <a href='https://github.com/firasm/jupyterbook_course_template' style='color:pink;'>template by clicking here</a>!"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  # google_analytics_id: UA-11111111 # add your Google Analytics Tracking Code
  comments:
    hypothesis: false
    utterances:
      repo: "UBC-CS/cpsc430"
    dokieli: false
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

# launch_buttons:
#   notebook_interface : "jupyterlab"
#   binderhub_url      : "https://mybinder.org"
#   thebe              : true

repository: 
  url          : https://github.com/UBC-CS/cpsc430
  path_to_book : ""
  branch       : main

sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['files']
    bibtex_reference_style: author_year
    myst_heading_anchors: true
    myst_heading_anchors: 3
    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - substitution

    myst_substitutions:
      # Instructor information
      INSTRUCTOR: "Dr. Firas Moosvi (he/his/him) and Ian"
      PRONOUNCE: "Fur-az Moose-vee"
      OFFICE: "ICCS 253"
      PHONE: "N/A"

      # Course Information
      COURSE_CODE: "CPSC 455"
      SECTION: "911"
      CREDITS: "3"
      TITLE: "Computers and Society"
      PREREQS: "Pre-reqs: 3 credits of Computer Science and at least third-year standing."
      COREQS: "N/A"
      TERM: "2024 Summer Term 1"
      ROOM: "DMP 110"
      MEETING_TIMES: "Monday, Wednesday, Friday 10:00 - 12:30"
      # FORMAT: "Lectures, Labs, Tutorials will all be running in-person."

      # Important Links
      CANVAS_ID: "140669"
      CANVAS_LINK: "https://canvas.ubc.ca/courses/CANVAS_ID"
      ZOOM_LINK: "[Zoom](https://canvas.ubc.ca/courses/CANVAS_ID/external_tools/15408)"
      ANNOUNCEMENTS_LINK: "[Canvas Announcements](https://canvas.ubc.ca/courses/CANVAS_ID/announcements)"
      COURSE_LINK: "https://firas.moosvi.com/courses/cpsc430/2024_S1/"
      FORUM_LINK: "[Ed Discussion](https://edstem.org/us/join/sguPRS)"
      TEXTBOOK: "Ethics for the Information Age, 8th Edition, by Michael J. Quinn."
      ANON_FEEDBACK: "[feedback form](https://ubc.ca1.qualtrics.com/?course=cpsc430&term=2024_S1)"
      ASSOCIATE_HEAD: "Associate Head [associate.head@fakeemail.ca](mailto:associate.head@fakeemail.ca)"
      ANALYTICS_OPTOUT: "[complete this form](https://ubc.ca1.qualtrics.com/jfe/form/SV_0p6lP4TtNpJn410/?course=cpsc430&term=2024_S1)"
      PERUSALL_ENROL: "https://app.perusall.com/join/moosvi-n8x4l"
      MTA_ENROL: "aurora100"

      # Withdrawal Dates and Exam Period
      # https://vancouver.calendar.ubc.ca/dates-and-deadlines
      W_DATE_1: "11:59 PDT on May 20, 2024"
      W_DATE_2: "11:59 PDT on June 07, 2024"
      W_DATE_3: "11:59 PDT on June 07, 2024"
      EXAM_PERIOD: "Monday June 24 - Friday June 28"

      # Course Policies
      GRACE_PERIOD: "6 hour"

      # TA Names
      TA1: "Maissan Bazazeh"
      TA1pronounce: ""
      TA2: "Rina Forristal"
      TA2pronounce: "MA-NU-SHREE"
      TA3: "Justin Rahardjo"
      TA3pronounce: ""
      TA4: "Mobina Shahbandeh"
      TA3pronounce: ""